swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Producer
  termsOfService: 'urn:tos'
host: 'localhost:8080'
basePath: /
tags:
  - name: message-controller
    description: Message Controller
paths:
  /api/1.0/message/send:
    get:
      tags:
        - message-controller
      summary: sendMessage
      operationId: sendMessageUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - message-controller
      summary: catchMessage
      operationId: catchMessageUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: query
          description: id
          required: true
          type: integer
          format: int64
        - name: options
          in: query
          description: options
          required: true
          type: string
        - name: date
          in: query
          description: date
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
